# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwinjectStoryboard.xcodeproj
    - IOS_SDK=iphonesimulator9.3
    - OSX_SDK=macosx10.11
    - TVOS_SDK=appletvsimulator9.2
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
#    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
#    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
#    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
#    - DESTINATION="OS=9.1,name=iPhone 6S" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO"
#    - DESTINATION="OS=9.2,name=iPhone 6S Plus" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="YES"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="YES"
    - DESTINATION="arch=x86_64" SCHEME="Swinject-OSX" SDK="$OSX_SDK" PLATFORM="Mac" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.0,name=Apple TV 1080p" SCHEME="Swinject-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO"
#    - DESTINATION="OS=9.1,name=Apple TV 1080p" SCHEME="Swinject-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO"
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SCHEME="Swinject-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO"
before_install:
  - git submodule update --recursive
  - echo "ENABLE_TESTABILITY = YES" >> Carthage/Checkouts/xcconfigs/Base/Configurations/Release.xcconfig
script:
  - set -o pipefail
  - xcodebuild -version
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO test
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO test
# Uncomment later
#  - if [ $POD_LINT == "YES" ]; then
#      pod lib lint --quick;
#    fi
notifications:
  email:
    on_success: never
